### ISSUE TITLE
Installing should not skip when versions are the same

### ISSUE THREAD

**Issue by taubenangriff** [anno-mods/iModYourAnno#119]
Users will want to reinstall the current version from time to time. Whether it is for troubleshooting, or just to be sure. 
Reinstalls should not be skipped when the user has "allow old versions to overwrite new" set to off, because forbidding downgrades and a reinstall are two different things IMO.

**Comment by jakobharder** [comment]
If I’m not mistaken it should already replace same versions if their hash is different.
Identical contents should not be updated, because then I don’t see after installing which mods actually changed.

**Comment by taubenangriff** [comment]
Ah okay, so the error message misled me.
