### ISSUE TITLE
Latest version labeled on Github as 0.3, shows up as 0.2.029 in window title.

### ISSUE THREAD

**Issue by michiel2304** [anno-mods/iModYourAnno#174]
![image](https://user-images.githubusercontent.com/14353193/208315397-74abdc3f-5f43-48e9-9ca4-f8b3e6b54385.png)

Latest download is supposed to be version 0.3 but the window shows as version 0.2.29

![image](https://user-images.githubusercontent.com/14353193/208315437-fabef427-0827-4192-9838-e1074690e80e.png)

**Comment by fabian91605** [comment]
same here! also wont start the game it says "Anno 1800 exited with Code 0":(
