### ISSUE TITLE
Launching problem

### ISSUE THREAD

**Issue by Grandmazer** [anno-mods/iModYourAnno#193]
I have installed all of .NET products( 6 and 7 versions) but i cant launch the app.... No error window or something else shows up. Nothing happens
what can cause this problem ?

**Comment by taubenangriff** [comment]
Should be related to #199

**Comment by taubenangriff** [comment]
It's a project file, not in the actual export. There will be a fix of this problem in the next release ofc, which will happen soon (tm).

**Comment by taubenangriff** [comment]
I hope the new update fixed it for you?
