### ISSUE TITLE
Trying to launch states incompatible with current version.

### ISSUE THREAD

**Issue by Zeradus** [anno-mods/iModYourAnno#201]
Trying to launch states incompatible with current version. As stated above I get a message stating that the current version is incompatible with Anno 1800 since they did a tiny update yesterday.

**Comment by Quizzey** [comment]
Same problem here.

**Comment by danoh24** [comment]
Same issue also

**Comment by taubenangriff** [comment]
For now, you need to uninstall your modloader. [Explanation here](https://www.reddit.com/r/anno/comments/12crnzw/message_from_unisoft/)

It should still work if you uninstalled the old loader, with one exception: The steam version needs a fix for the game launch.

**Comment by Zeradus** [comment]
The only modloader I installed was when I clicked install from the button on the mod manager. Would you happen to know what that modloader is called as I can't seem to find it?

**Comment by taubenangriff** [comment]
The new modloader is directly integrated in 1800 now, you don't need to install a new one, only uninstall the old one.

**Comment by Zeradus** [comment]
I understand that..........I don't know where the mod manager installed the existing one. I never downloaded a standalone modloader, the only thing related to a modloader was when I installed your mod manager, saw modloader, and clicked install. I am unsure as to where that file gets installed at so I have no idea where it is or what it is called.

**Comment by taubenangriff** [comment]
It's no problem really. We built a tool that does it for you, so you don't have to know it.

The next release will autodetect if the old modloader is still installed and then give you an option to uninstall it.

**Comment by Zeradus** [comment]
Thank you very much!!!!
