### ISSUE TITLE
File Wide Description

### ISSUE THREAD

**Issue by taubenangriff** [anno-mods/iModYourAnno#219]
From @Hier0nimus on Discord

"A SubTitle would be nice as a <ImyaTweaks> to have some more possibilities for hierarchy within one file/section. No need for collapsing. Only a subtitle would already be nice to have.
It would solve the biggest problem I encounter now, wanting to group more things together. "

**Comment by Hier0nimus** [comment]
I would even expand this if possible... 

ICON with LABEL/DESCRIPTION next to it
As a subheader of a section
And maybe also as a header of the section

So I can make Sections for TU, AL, HO, TH, ships,... with icon + label
And then in that section icons of the specialists + label of the specialists

**Comment by taubenangriff** [comment]
No subheaders for now - as Tweaks might get a big makeover to support groups in the future, this is a better opportunity to do it. 

But Here you go: Icon + Description.

**Comment by taubenangriff** [comment]
![image](https://github.com/anno-mods/iModYourAnno/assets/51975164/577ab14c-9d7b-4b13-abd7-4a98f79d535f)
