### ISSUE TITLE
Improve readability of incompatability warnings by using newlines

### ISSUE THREAD

**Issue by Cyclonit** [anno-mods/iModYourAnno#224]
If a mod is incompatible with multiple mods, their names are shown in a single line with "," between them. New-lines should be used instead to improve readability.
![image](https://github.com/anno-mods/iModYourAnno/assets/19320074/c2441963-4be5-41ee-8b6d-c48b06d80132)

Proposal:
```
Compatability Errors:
- [Gameplay] Coffee and Tobacoo in Enbesa
- [Gameplay] Coffee and Tobacoo in Enbesa - Light
- [Gameplay] Coffee and Tobacco in Enbesa - Farms Only
```

**Comment by taubenangriff** [comment]
Thanks for the proposal, will land in the next version.

![image](https://github.com/anno-mods/iModYourAnno/assets/51975164/2cfd98d5-d7bc-4ec8-b061-95aecaf5ad99)
