### ISSUE TITLE
Uninstall mod loader button if installed

### ISSUE THREAD

**Issue by EtienneDx** [anno-mods/iModYourAnno#57]
When the mod loader is installed, it would be nice to have a way to uninstall it or update it.
This would require to keep a backup of the original python35.dll file.

I'd say the way to do this would be adding a disabled uninstall button, enabling it only when possible

**Comment by taubenangriff** [comment]
![image](https://user-images.githubusercontent.com/51975164/165084671-a0ccd7a3-1ed0-4e39-b374-fc593b247e6f.png)

I propose this

**Comment by EtienneDx** [comment]
Could work yeah, switching python35.dll and python35.dll.vanilla or something. The auto update is nice too

**Comment by jakobharder** [comment]
![image](https://user-images.githubusercontent.com/12190313/167080604-2bc0a759-c5fa-46af-8dae-37370f81b22d.png)

Disabling the modloader is a rather high level action and not something I would hide in the installation page. Also considering someone may look for a "deactivate all" option.

I'd prefer the toggle directly under the start button.
